//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarvellousWorks.PracticalPattern.Proxy.Tests.RemoteSubject {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RemoteSubject.ISubject")]
    public interface ISubject {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubject/Request", ReplyAction="http://tempuri.org/ISubject/RequestResponse")]
        string Request();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISubjectChannel : MarvellousWorks.PracticalPattern.Proxy.Tests.RemoteSubject.ISubject, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SubjectClient : System.ServiceModel.ClientBase<MarvellousWorks.PracticalPattern.Proxy.Tests.RemoteSubject.ISubject>, MarvellousWorks.PracticalPattern.Proxy.Tests.RemoteSubject.ISubject {
        
        public SubjectClient() {
        }
        
        public SubjectClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SubjectClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SubjectClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SubjectClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Request() {
            return base.Channel.Request();
        }
    }
}
